files:
- generatedChecksum: 99DB74296DF9943C474F4F03A700C790
  logicalPath: config/pic32mx470_curiosity
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 99DB74296DF9943C474F4F03A700C790
- generatedChecksum: 4FB179047B6E62584168547FB348A3C6
  logicalPath: config/pic32mx470_curiosity
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4FB179047B6E62584168547FB348A3C6
- generatedChecksum: 18E32DE548F86F61D51009B77E965A1A
  logicalPath: config/pic32mx470_curiosity
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 18E32DE548F86F61D51009B77E965A1A
- generatedChecksum: null
  logicalPath: ''
  name: main_pic32mx470.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 8C30447613ABE14B1BF49F92A6BBB7D7
  logicalPath: config/pic32mx470_curiosity/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 8C30447613ABE14B1BF49F92A6BBB7D7
- generatedChecksum: F8BB2BAA74068083A80E6E229BBCF3E3
  logicalPath: config/pic32mx470_curiosity/peripheral/coretimer
  name: plib_coretimer.c
  physicalPath: peripheral/coretimer
  security: NON_SECURE
  type: SOURCE
  userChecksum: F8BB2BAA74068083A80E6E229BBCF3E3
- generatedChecksum: B8E5065EC27C7A8E63FC4AB257C57023
  logicalPath: config/pic32mx470_curiosity/peripheral/dmac
  name: plib_dmac.c
  physicalPath: peripheral/dmac
  security: NON_SECURE
  type: SOURCE
  userChecksum: B8E5065EC27C7A8E63FC4AB257C57023
- generatedChecksum: 4AC106B5C3CA55FE4768E0B65530328F
  logicalPath: config/pic32mx470_curiosity/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4AC106B5C3CA55FE4768E0B65530328F
- generatedChecksum: C00E8D1AD34AD6168A52BCCF9209E95F
  logicalPath: config/pic32mx470_curiosity/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: C00E8D1AD34AD6168A52BCCF9209E95F
- generatedChecksum: 601C98B1D85E5A9386FCC8D02E15064D
  logicalPath: config/pic32mx470_curiosity/peripheral/spi/spi_master
  name: plib_spi1_master.c
  physicalPath: peripheral/spi/spi_master
  security: NON_SECURE
  type: SOURCE
  userChecksum: 601C98B1D85E5A9386FCC8D02E15064D
- generatedChecksum: 58938B55AF7E47EF71BC7FEE542C57B0
  logicalPath: config/pic32mx470_curiosity/peripheral/tmr
  name: plib_tmr2.c
  physicalPath: peripheral/tmr
  security: NON_SECURE
  type: SOURCE
  userChecksum: 58938B55AF7E47EF71BC7FEE542C57B0
- generatedChecksum: 5733E7E141B78CCE3D7F5714E6ACA902
  logicalPath: config/pic32mx470_curiosity/peripheral/uart
  name: plib_uart2.c
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 5733E7E141B78CCE3D7F5714E6ACA902
- generatedChecksum: 7806B30ECAE0D18D08CD583D8775530D
  logicalPath: config/pic32mx470_curiosity/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7806B30ECAE0D18D08CD583D8775530D
- generatedChecksum: 4FCD44F0F9E8E1C437AEB7629F691381
  logicalPath: config/pic32mx470_curiosity
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4FCD44F0F9E8E1C437AEB7629F691381
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mx470_curiosity
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mx470_curiosity
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mx470_curiosity/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: C9591F8126D956F31100408015A41568
  logicalPath: config/pic32mx470_curiosity/peripheral/coretimer
  name: plib_coretimer.h
  physicalPath: peripheral/coretimer
  security: NON_SECURE
  type: HEADER
  userChecksum: C9591F8126D956F31100408015A41568
- generatedChecksum: FE97A53898E1188374A5846B088F5BE6
  logicalPath: config/pic32mx470_curiosity/peripheral/dmac
  name: plib_dmac.h
  physicalPath: peripheral/dmac
  security: NON_SECURE
  type: HEADER
  userChecksum: FE97A53898E1188374A5846B088F5BE6
- generatedChecksum: A2CC849C687144A046545E8CF6188343
  logicalPath: config/pic32mx470_curiosity/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: A2CC849C687144A046545E8CF6188343
- generatedChecksum: AD66E04F4F5DB48E7550DFDB79DF075E
  logicalPath: config/pic32mx470_curiosity/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: AD66E04F4F5DB48E7550DFDB79DF075E
- generatedChecksum: 27EFFF00EA5DD882C446A714F0D9CE9E
  logicalPath: config/pic32mx470_curiosity/peripheral/spi/spi_master
  name: plib_spi1_master.h
  physicalPath: peripheral/spi/spi_master
  security: NON_SECURE
  type: HEADER
  userChecksum: 27EFFF00EA5DD882C446A714F0D9CE9E
- generatedChecksum: CFA758C8B7258190473EF7C60C4BA4E9
  logicalPath: config/pic32mx470_curiosity/peripheral/spi/spi_master
  name: plib_spi_master_common.h
  physicalPath: peripheral/spi/spi_master
  security: NON_SECURE
  type: HEADER
  userChecksum: CFA758C8B7258190473EF7C60C4BA4E9
- generatedChecksum: 951CB6B720EFCD3044875413BC7D7773
  logicalPath: config/pic32mx470_curiosity/peripheral/tmr
  name: plib_tmr2.h
  physicalPath: peripheral/tmr
  security: NON_SECURE
  type: HEADER
  userChecksum: 951CB6B720EFCD3044875413BC7D7773
- generatedChecksum: D948F2CE092CAB556EF299D3CCD83A55
  logicalPath: config/pic32mx470_curiosity/peripheral/tmr
  name: plib_tmr_common.h
  physicalPath: peripheral/tmr
  security: NON_SECURE
  type: HEADER
  userChecksum: D948F2CE092CAB556EF299D3CCD83A55
- generatedChecksum: 316D6B34B34BF612D47E310073FD397D
  logicalPath: config/pic32mx470_curiosity/peripheral/uart
  name: plib_uart2.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 316D6B34B34BF612D47E310073FD397D
- generatedChecksum: 91611515A95D92B82B7F4064C16D122B
  logicalPath: config/pic32mx470_curiosity/peripheral/uart
  name: plib_uart_common.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 91611515A95D92B82B7F4064C16D122B
- generatedChecksum: 7DC91D6D376C98802C9C2990432DE9B7
  logicalPath: config/pic32mx470_curiosity
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 7DC91D6D376C98802C9C2990432DE9B7
- generatedChecksum: 52AA20E8BAA488B3B6581379249C0FCE
  logicalPath: config/pic32mx470_curiosity
  name: p32MX470F512H.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 52AA20E8BAA488B3B6581379249C0FCE
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mx470_curiosity;
- append: false
  category: C32
  delimiter: ''
  key: generate-16-bit-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mx470_curiosity;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-16-bit-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
