configName: pic32mx470_curiosity
folderName: ''
format_version: v1.0
frameworkPath: D:\Projects\git_hub
processor: PIC32MX470F512H
projectName: ''
settings:
  PackageFilter: bsp;core;core_apps_pic32mx;csp;csp_apps_pic32mx;dev_packs;quick_docs;reference_apps;usb
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32MX_DFP\1.5.259\atdf\PIC32MX470F512H.atdf
